# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoa" do
  version "0.0.2"

  on_macos do
    sha256 "51f887e25350654a9fabe99f8053ce65088be8c02cea8a78bb7d81c633caa0b7"
    url "https://github.com/jamescalam/stoa/releases/download/v#{version}/stoa_#{version}_darwin_all.tar.gz"
  end

  name "stoa"
  desc "Minimal in-terminal music radio with a Greco-Roman visualizer"
  homepage "https://github.com/jamescalam/stoa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoa"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stoa"]
  end

  # No zap stanza required

end
