# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoa" do
  version "0.0.5"

  on_macos do
    sha256 "e25d31634abe9eeb53cba0f9268112fd1d7231548699c3c9492d2fa6b58b37be"
    url "https://github.com/jamescalam/stoa/releases/download/v#{version}/stoa_#{version}_darwin_all.tar.gz"
  end

  name "stoa"
  desc "Minimal in-terminal music radio with a Greco-Roman visualizer"
  homepage "https://github.com/jamescalam/stoa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoa"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stoa"]
  end

  # No zap stanza required
end
