# This file was generated by GoReleaser. DO NOT EDIT.
cask "stoa" do
  version "0.0.4"

  on_macos do
    sha256 "de3c10f8497afd8dd1eb0f291f97c482238a61f4bccdb7b7330905a826231a3a"
    url "https://github.com/jamescalam/stoa/releases/download/v#{version}/stoa_#{version}_darwin_all.tar.gz"
  end

  name "stoa"
  desc "Minimal in-terminal music radio with a Greco-Roman visualizer"
  homepage "https://github.com/jamescalam/stoa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stoa"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stoa"]
  end

  # No zap stanza required

end
